name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.

#name: Gitleaks

#on:
#  pull_request:
#    paths:
#      - '**/*.go'
#      - '**/*.py'
#      - '**/*.js'
#      - '**/*.ts'
#      - '**/*.rb'
#      - '**/*.java'
#      - '**/*.c'
#      - '**/*.cpp'
#      - '**/*.h'
#      - '**/*.sh'
#      - '**/*.yaml'
#      - '**/*.yml'

#jobs:
#  gitleaks:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Set up Gitleaks
#        uses: zricethezav/gitleaks-action@v1
#        with:
#          config: '.gitleaks.toml'  # Optional: specify your custom Gitleaks config file if you have one
#          path: '.'  # Optional: specify the path to scan if different from the root

#      - name: Run Gitleaks
#        run: gitleaks --path=. --config=.gitleaks.toml
