name: Block Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Block Direct Push
        run: |
          echo "Direct pushes to the main branch are not allowed. Reverting the push."
          git revert HEAD --no-edit
          git push origin main
          exit 1
