name: Block Direct Push to Master

on:
  push:
    branches:
      - main

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is direct
        run: |
          echo "Direct pushes to the master branch are not allowed. Please create a pull request instead."
          exit 1
